import numpy as np


class SGD:
    """Stochastic Gradient Descent optimizer."""

    def __init__(self, parameters, lr=0.01):
        """Store parameter tensors and the learning rate."""
        # We pass in the list generated by model.parameters()
        self.parameters = parameters
        self.lr = lr

    def step(self):
        """Updates the parameters using the accumulated gradients."""
        for p in self.parameters:
            # We update the raw NumPy array directly.
            # This prevents the update from being tracked in the autograd graph.
            p.data -= self.lr * p.grad

    def zero_grad(self):
        for p in self.parameters:
            if p.grad is not None:
                # Again, use the slice operator [:] for in-place mutation
                p.grad[:] = 0


class Adam:
    """Adam (Adaptive Moment Estimation) optimizer."""

    def __init__(self, parameters, lr=0.001, betas=(0.9, 0.999), eps=1e-8):
        """Initialize Adam hyperparameters and moment buffers."""
        self.parameters = parameters
        self.lr = lr
        self.beta1, self.beta2 = betas
        self.eps = eps
        self.t = 0  # Time step counter

        # Initialize first (m) and second (v) moment vectors as zeros
        self.m = [np.zeros_like(p.data) for p in self.parameters]
        self.v = [np.zeros_like(p.data) for p in self.parameters]

    def step(self):
        """Perform one Adam optimization step for all parameters."""
        self.t += 1

        for i, p in enumerate(self.parameters):
            grad = p.grad

            # 1. Update biased first moment estimate
            self.m[i] = self.beta1 * self.m[i] + (1 - self.beta1) * grad

            # 2. Update biased second raw moment estimate
            self.v[i] = self.beta2 * self.v[i] + (1 - self.beta2) * (grad**2)

            # 3. Compute bias-corrected moment estimates
            m_hat = self.m[i] / (1 - self.beta1**self.t)
            v_hat = self.v[i] / (1 - self.beta2**self.t)

            # 4. Update the raw NumPy array directly
            p.data -= self.lr * m_hat / (np.sqrt(v_hat) + self.eps)

    def zero_grad(self):
        for p in self.parameters:
            if p.grad is not None:
                # Again, use the slice operator [:] for in-place mutation
                p.grad[:] = 0